### ISSUE TITLE
problem in fine-grained classification

### ISSUE THREAD

**Issue by lihy-1224** [hardiksinghnegi/Neural_Sentiment_Analysis#1]
In fine-grained mode, dev percentage is more than 80% in my test, but the result in paper is about 50%. I just wonder how to test the fine-grained classification correctly, thx~

**Comment by hardiksinghnegi** [comment]
Fine-grained isn't fully tested as of yet, it still needs reviewing.

**Comment by lexus1224** [comment]
**ttpro1995** also say he have not fully test on fine grain classification yet in his **TreeLSTMSentiment** project. Does it mean that we should fix code bugs to match with original paper result?

**Comment by lexus1224** [comment]
Another question is in constituency model, there was an error when I run the code:
```
line 174, in get_child_state
    rc, rh = tree.children[1].state
IndexError: list index out of range
```
How was this handled when you were testing?

**Comment by lihy-1224** [comment]
I fix it after delete pth file in **./data** (maybe I use binary preprocess data for fine grain)

**Comment by lexus1224** [comment]
When I set _attention_flag_ True in binary mode, the dev percentage seems to be lower then without attention mechanism. Is it right in your test?

**Comment by lexus1224** [comment]
When I set attention_flag True in binary mode, the test percentage seems to be lower than without attention mechanism. Is it right in your test?
