### ISSUE TITLE
accuracy with attention mechanism

### ISSUE THREAD

**Issue by lihy-1224** [hardiksinghnegi/Neural_Sentiment_Analysis#2]
When I set attention_flag True in binary mode, the test accuracy seems to be lower than without attention mechanism. Is it right in your test?

**Comment by venusafroid** [comment]
> 
> 
> When I set attention_flag True in binary mode, the test accuracy seems to be lower than without attention mechanism. Is it right in your test?

hi,
when I use java to get parents.txt of sentences, I can not find the packages like edu.stanford.nlp.ling. Can you tell me how the fix it?? Thank you very much!
